// src/components/sidenav/Sidenav.jsx
import { NavLink } from 'react-router';
import logo from '../../assets/foliole-big.svg';
import './Sidenav.css';
import { routes } from '../../utilities/routes';

function Sidenav() {
  return (
    <nav className="fo-navigation navigation">
      <img src={logo} alt="Foliole brand icon" className="fo-p-block-end-1" />
      <ul className="fo-navigation-list">
        <li>
          <NavLink
            to={routes.home.path}
            className={({ isActive }) =>
              `fo-button fo-button-flat fo-text-bold${
                isActive ? ' active' : ''
              }`
            }
          >
            {routes.home.name}
          </NavLink>
        </li>

        <li>
          <NavLink
            to={routes.components.path}
            className={({ isActive }) =>
              `fo-button fo-button-flat fo-text-bold${
                isActive ? ' active' : ''
              }`
            }
          >
            {routes.components.name}
          </NavLink>
        </li>
        <ul className="fo-navigation-list">
          <li>
            <NavLink
              to={routes.badge.path}
              className={({ isActive }) =>
                `fo-button fo-button-flat${isActive ? ' active' : ''}`
              }
            >
              {routes.badge.name}
            </NavLink>
          </li>
          <li>
            <NavLink
              to={routes.button.path}
              className={({ isActive }) =>
                `fo-button fo-button-flat${isActive ? ' active' : ''}`
              }
            >
              {routes.button.name}
            </NavLink>
          </li>
          <li>
            <NavLink
              to={routes.card.path}
              className={({ isActive }) =>
                `fo-button fo-button-flat${isActive ? ' active' : ''}`
              }
            >
              {routes.card.name}
            </NavLink>
          </li>
          <li>
            <NavLink
              to={routes.checkbox.path}
              className={({ isActive }) =>
                `fo-button fo-button-flat${isActive ? ' active' : ''}`
              }
            >
              {routes.checkbox.name}
            </NavLink>
          </li>
          <li>
            <NavLink
              to={routes.link.path}
              className={({ isActive }) =>
                `fo-button fo-button-flat${isActive ? ' active' : ''}`
              }
            >
              {routes.link.name}
            </NavLink>
          </li>
          <li>
            <NavLink
              to={routes.navigation.path}
              className={({ isActive }) =>
                `fo-button fo-button-flat${isActive ? ' active' : ''}`
              }
            >
              {routes.navigation.name}
            </NavLink>
          </li>
          <li>
            <NavLink
              to={routes.radioButton.path}
              className={({ isActive }) =>
                `fo-button fo-button-flat${isActive ? ' active' : ''}`
              }
            >
              {routes.radioButton.name}
            </NavLink>
          </li>
          <li>
            <NavLink
              to={routes.select.path}
              className={({ isActive }) =>
                `fo-button fo-button-flat${isActive ? ' active' : ''}`
              }
            >
              {routes.select.name}
            </NavLink>
          </li>
          <li>
            <NavLink
              to={routes.textField.path}
              className={({ isActive }) =>
                `fo-button fo-button-flat${isActive ? ' active' : ''}`
              }
            >
              {routes.textField.name}
            </NavLink>
          </li>
        </ul>

        <li>
          <NavLink
            to={routes.utilities.path}
            className={({ isActive }) =>
              `fo-button fo-button-flat fo-text-bold${
                isActive ? ' active' : ''
              }`
            }
          >
            {routes.utilities.name}
          </NavLink>
        </li>
        <ul className="fo-navigation-list">
          <li>
            <NavLink
              to={routes.classes.path}
              className={({ isActive }) =>
                `fo-button fo-button-flat${isActive ? ' active' : ''}`
              }
            >
              {routes.classes.name}
            </NavLink>
          </li>
          <li>
            <NavLink
              to={routes.properties.path}
              className={({ isActive }) =>
                `fo-button fo-button-flat${isActive ? ' active' : ''}`
              }
            >
              {routes.properties.name}
            </NavLink>
          </li>
        </ul>
      </ul>
    </nav>
  );
}

export default Sidenav;

// src/sidenav/Sidenav.svelte
<script>
  import { Link, useLocation } from 'svelte-navigator';
  const location = useLocation();
</script>

<aside class="side-nav">
  <img
    src="/assets/foliole.svg"
    alt="Foliole brand icon"
    class="fo-padding-left-1 fo-padding-bottom-1"
  />
  <nav>
    {#if $location.pathname !== '/'}
      <ul class="side-nav-list">
        <li>
          <Link to="/" class="fo-button fo-button-flat">{'← Home'}</Link>
        </li>
      </ul>
    {/if}

    {#if $location.pathname === '/'}
      <ul class="side-nav-list">
        <li>
          <Link to="components/" class="fo-button fo-button-flat"
            >Components</Link
          >
        </li>
        <li>
          <Link to="utilities/" class="fo-button fo-button-flat">Utilities</Link
          >
        </li>
      </ul>
    {/if}

    {#if $location.pathname.includes('/components')}
      <ul class="side-nav-list">
        <li>
          <Link to="components" class="fo-button fo-button-flat"
            >Components overview</Link
          >
        </li>
        <li>
          <Link to="components/buttons" class="fo-button fo-button-flat"
            >Buttons</Link
          >
        </li>
        <li>
          <Link to="components/links" class="fo-button fo-button-flat"
            >Links</Link
          >
        </li>
        <li>
          <Link to="components/text-fields" class="fo-button fo-button-flat"
            >Text fields</Link
          >
        </li>
        <li>
          <Link to="components/select" class="fo-button fo-button-flat"
            >Select</Link
          >
        </li>
        <li>
          <Link to="components/radio-buttons" class="fo-button fo-button-flat"
            >Radio buttons</Link
          >
        </li>
        <li>
          <Link to="components/checkboxes" class="fo-button fo-button-flat"
            >Checkboxes</Link
          >
        </li>
        <li>
          <Link to="components/badges" class="fo-button fo-button-flat"
            >Badges</Link
          >
        </li>
        <li>
          <Link to="components/cards" class="fo-button fo-button-flat"
            >Cards</Link
          >
        </li>
      </ul>
    {/if}

    {#if $location.pathname.includes('/utilities')}
      <ul class="side-nav-list">
        <li>
          <Link to="utilities" class="fo-button fo-button-flat"
            >Utilities overview</Link
          >
        </li>
      </ul>
    {/if}
  </nav>
</aside>

<style>
  .side-nav {
    position: sticky;
    top: calc(var(--fo-spacing) * 2);
    align-self: start;
    gap: var(--fo-spacing);
  }

  .side-nav-list {
    display: flex;
    flex-direction: column;
    list-style: none;
    margin: 0;
    padding: 0;
  }

  .side-nav-list li {
    display: block;
    margin: 0;
    padding: 0;
  }
</style>
